In [1]:
3+3

6

In [1]:
print(2+3)

5


In [3]:
print('Hello, AI/MLUT2021 Batch Pythonistas')

Hello, AI/MLUT2021 Batch Pythonistas


In [3]:
a=5

print('A times 5 equals', a*5)

A times 5 equals 25


In [7]:
a=2

print('A times ten equals To =', a*10)

A times ten equals To = 20


In [4]:
great_list = ['Python', 5, 'Scripts', 5, 'OS', 4]

print(great_list)

print(great_list[0])

print(great_list[3])

print(great_list[-2])

print(len(great_list))

print(len(great_list))

['Python', 5, 'Scripts', 5, 'OS', 4]
Python
5
OS
6
6


In [10]:
great_list[1] = 22
print(great_list[1])
great_list.append('to the back')
print(great_list)
print(len(great_list))
great_list.pop(4)
print(great_list)

22
['Python', 22, 'Scripts', 5, 'OS', 4, 'to the back', 'to the back', 'to the back']
9
['Python', 22, 'Scripts', 5, 4, 'to the back', 'to the back', 'to the back']


In [13]:
repeated_list= [6]*3
print(repeated_list)

[6, 6, 6]


In [14]:
great_list[2]=[3,4,5]
print(great_list)

['Python', 22, [3, 4, 5], 5, 4, 'to the back', 'to the back', 'to the back']


In [3]:
import numpy as np
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[1][1])
np.save('npsavetoFile',matrix)


5


In [6]:
np.savez('zipped_file_name', mat_save=matrix)

In [8]:
load_vec = np.load('npsaveTofile.npy')
print(load_vec)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [1]:
import numpy as np
matrix = np.array([[-1,2,3],[4,-5,6],[7,-8,9]])
print(matrix[matrix>0])

[2 3 4 6 7 9]


In [2]:
import pandas as pd
auto = pd.read_csv('Automobile.csv') 
auto.head()

symboling  normalized_losses         make fuel_type aspiration  \
0          3                168  alfa-romero       gas        std   
1          3                168  alfa-romero       gas        std   
2          1                168  alfa-romero       gas        std   
3          2                164         audi       gas        std   
4          2                164         audi       gas        std   

  number_of_doors   body_style drive_wheels engine_location  wheel_base  ...  \
0             two  convertible          rwd           front        88.6  ...   
1             two  convertible          rwd           front        88.6  ...   
2             two    hatchback          rwd           front        94.5  ...   
3            four        sedan          fwd           front        99.8  ...   
4            four        sedan          4wd           front        99.4  ...   

   engine_size  fuel_system  bore  stroke compression_ratio horsepower  \
0          130         mpfi  3.47    2.68               9.0        111   
1          130         mpfi  3.47    2.68               9.0        111   
2          152         mpfi  2.68    3.47               9.0        154   
3          109         mpfi  3.19    3.40              10.0        102   
4          136         mpfi  3.19    3.40               8.0        115   

   peak_rpm city_mpg  highway_mpg  price  
0      5000       21           27  13495  
1      5000       21           27  16500  
2      5000       19           26  16500  
3      5500       24           30  13950  
4      5500       18           22  17450  

[5 rows x 26 columns]